name: flutter_google_places
description: Google places autocomplete widgets for flutter. No wrapper, use https://pub.dev/packages/google_maps_webservice
version: 1.3.5

publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_api_headers: ^4.2.4
  google_maps_webservice:
    git:
      url: https://github.com/parthvirani-oceanmtech/google_maps_webservice.git
      ref: 752f417c9ab559889b2a73b4cda331ea61913259
  http: ^1.0.0
  rxdart: ^0.27.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.10.0

flutter:
  assets:
    - packages/flutter_google_places/assets/google_black.png
    - packages/flutter_google_places/assets/google_white.png
